'use strict';

module.exports = [
    { value: 'Aceguá' },
    { value: 'Água Santa' },
    { value: 'Agudo' },
    { value: 'Ajuricaba' },
    { value: 'Alecrim' },
    { value: 'Alegrete' },
    { value: 'Alegria' },
    { value: 'Almirante Tamandaré do Sul' },
    { value: 'Alpestre' },
    { value: 'Alto Alegre' },
    { value: 'Alto Feliz' },
    { value: 'Alvorada' },
    { value: 'Amaral Ferrador' },
    { value: 'Ametista do Sul' },
    { value: 'André da Rocha' },
    { value: 'Anta Gorda' },
    { value: 'Antônio Prado' },
    { value: 'Arambaré' },
    { value: 'Araricá' },
    { value: 'Aratiba' },
    { value: 'Arroio do Meio' },
    { value: 'Arroio do Sal' },
    { value: 'Arroio do Padre' },
    { value: 'Arroio dos Ratos' },
    { value: 'Arroio do Tigre' },
    { value: 'Arroio Grande' },
    { value: 'Arvorezinha' },
    { value: 'Augusto Pestana' },
    { value: 'Áurea' },
    { value: 'Bagé' },
    { value: 'Balneário Pinhal' },
    { value: 'Barão' },
    { value: 'Barão de Cotegipe' },
    { value: 'Barão do Triunfo' },
    { value: 'Barracão' },
    { value: 'Barra do Guarita' },
    { value: 'Barra do Quaraí' },
    { value: 'Barra do Ribeiro' },
    { value: 'Barra do Rio Azul' },
    { value: 'Barra Funda' },
    { value: 'Barros Cassal' },
    { value: 'Benjamin Constant do Sul' },
    { value: 'Bento Gonçalves' },
    { value: 'Boa Vista das Missões' },
    { value: 'Boa Vista do Buricá' },
    { value: 'Boa Vista do Cadeado' },
    { value: 'Boa Vista do Incra' },
    { value: 'Boa Vista do Sul' },
    { value: 'Bom Jesus' },
    { value: 'Bom Princípio' },
    { value: 'Bom Progresso' },
    { value: 'Bom Retiro do Sul' },
    { value: 'Boqueirão do Leão' },
    { value: 'Bossoroca' },
    { value: 'Bozano' },
    { value: 'Braga' },
    { value: 'Brochier' },
    { value: 'Butiá' },
    { value: 'Caçapava do Sul' },
    { value: 'Cacequi' },
    { value: 'Cachoeira do Sul' },
    { value: 'Cachoeirinha' },
    { value: 'Cacique Doble' },
    { value: 'Caibaté' },
    { value: 'Caiçara' },
    { value: 'Camaquã' },
    { value: 'Camargo' },
    { value: 'Cambará do Sul' },
    { value: 'Campestre da Serra' },
    { value: 'Campina das Missões' },
    { value: 'Campinas do Sul' },
    { value: 'Campo Bom' },
    { value: 'Campo Novo' },
    { value: 'Campos Borges' },
    { value: 'Candelária' },
    { value: 'Cândido Godói' },
    { value: 'Candiota' },
    { value: 'Canela' },
    { value: 'Canguçu' },
    { value: 'Canoas' },
    { value: 'Canudos do Vale' },
    { value: 'Capão Bonito do Sul' },
    { value: 'Capão da Canoa' },
    { value: 'Capão do Cipó' },
    { value: 'Capão do Leão' },
    { value: 'Capivari do Sul' },
    { value: 'Capela de Santana' },
    { value: 'Capitão' },
    { value: 'Carazinho' },
    { value: 'Caraá' },
    { value: 'Carlos Barbosa' },
    { value: 'Carlos Gomes' },
    { value: 'Casca' },
    { value: 'Caseiros' },
    { value: 'Catuípe' },
    { value: 'Caxias do Sul' },
    { value: 'Centenário' },
    { value: 'Cerrito' },
    { value: 'Cerro Branco' },
    { value: 'Cerro Grande' },
    { value: 'Cerro Grande do Sul' },
    { value: 'Cerro Largo' },
    { value: 'Chapada' },
    { value: 'Charqueadas' },
    { value: 'Charrua' },
    { value: 'Chiapetta' },
    { value: 'Chuí' },
    { value: 'Chuvisca' },
    { value: 'Cidreira' },
    { value: 'Ciríaco' },
    { value: 'Colinas' },
    { value: 'Colorado' },
    { value: 'Condor' },
    { value: 'Constantina' },
    { value: 'Coqueiro Baixo' },
    { value: 'Coqueiros do Sul' },
    { value: 'Coronel Barros' },
    { value: 'Coronel Bicaco' },
    { value: 'Coronel Pilar' },
    { value: 'Cotiporã' },
    { value: 'Coxilha' },
    { value: 'Crissiumal' },
    { value: 'Cristal' },
    { value: 'Cristal do Sul' },
    { value: 'Cruz Alta' },
    { value: 'Cruzaltense' },
    { value: 'Cruzeiro do Sul' },
    { value: 'David Canabarro' },
    { value: 'Derrubadas' },
    { value: 'Dezesseis de Novembro' },
    { value: 'Dilermando de Aguiar' },
    { value: 'Dois Irmãos' },
    { value: 'Dois Irmãos das Missões' },
    { value: 'Dois Lajeados' },
    { value: 'Dom Feliciano' },
    { value: 'Dom Pedro de Alcântara' },
    { value: 'Dom Pedrito' },
    { value: 'Dona Francisca' },
    { value: 'Doutor Maurício Cardoso' },
    { value: 'Doutor Ricardo' },
    { value: 'Eldorado do Sul' },
    { value: 'Encantado' },
    { value: 'Encruzilhada do Sul' },
    { value: 'Engenho Velho' },
    { value: 'Entre-Ijuís' },
    { value: 'Entre Rios do Sul' },
    { value: 'Erebango' },
    { value: 'Erechim' },
    { value: 'Ernestina' },
    { value: 'Herval' },
    { value: 'Erval Grande' },
    { value: 'Erval Seco' },
    { value: 'Esmeralda' },
    { value: 'Esperança do Sul' },
    { value: 'Espumoso' },
    { value: 'Estação' },
    { value: 'Estância Velha' },
    { value: 'Esteio' },
    { value: 'Estrela' },
    { value: 'Estrela Velha' },
    { value: 'Eugênio de Castro' },
    { value: 'Fagundes Varela' },
    { value: 'Farroupilha' },
    { value: 'Faxinal do Soturno' },
    { value: 'Faxinalzinho' },
    { value: 'Fazenda Vilanova' },
    { value: 'Feliz' },
    { value: 'Flores da Cunha' },
    { value: 'Floriano Peixoto' },
    { value: 'Fontoura Xavier' },
    { value: 'Formigueiro' },
    { value: 'Forquetinha' },
    { value: 'Fortaleza dos Valos' },
    { value: 'Frederico Westphalen' },
    { value: 'Garibaldi' },
    { value: 'Garruchos' },
    { value: 'Gaurama' },
    { value: 'General Câmara' },
    { value: 'Gentil' },
    { value: 'Getúlio Vargas' },
    { value: 'Giruá' },
    { value: 'Glorinha' },
    { value: 'Gramado' },
    { value: 'Gramado dos Loureiros' },
    { value: 'Gramado Xavier' },
    { value: 'Gravataí' },
    { value: 'Guabiju' },
    { value: 'Guaíba' },
    { value: 'Guaporé' },
    { value: 'Guarani das Missões' },
    { value: 'Harmonia' },
    { value: 'Herveiras' },
    { value: 'Horizontina' },
    { value: 'Hulha Negra' },
    { value: 'Humaitá' },
    { value: 'Ibarama' },
    { value: 'Ibiaçá' },
    { value: 'Ibiraiaras' },
    { value: 'Ibirapuitã' },
    { value: 'Ibirubá' },
    { value: 'Igrejinha' },
    { value: 'Ijuí' },
    { value: 'Ilópolis' },
    { value: 'Imbé' },
    { value: 'Imigrante' },
    { value: 'Independência' },
    { value: 'Inhacorá' },
    { value: 'Ipê' },
    { value: 'Ipiranga do Sul' },
    { value: 'Iraí' },
    { value: 'Itaara' },
    { value: 'Itacurubi' },
    { value: 'Itapuca' },
    { value: 'Itaqui' },
    { value: 'Itati' },
    { value: 'Itatiba do Sul' },
    { value: 'Ivorá' },
    { value: 'Ivoti' },
    { value: 'Jaboticaba' },
    { value: 'Jacuizinho' },
    { value: 'Jacutinga' },
    { value: 'Jaguarão' },
    { value: 'Jaguari' },
    { value: 'Jaquirana' },
    { value: 'Jari' },
    { value: 'Jóia' },
    { value: 'Júlio de Castilhos' },
    { value: 'Lagoa Bonita do Sul' },
    { value: 'Lagoão' },
    { value: 'Lagoa dos Três Cantos' },
    { value: 'Lagoa Vermelha' },
    { value: 'Lajeado' },
    { value: 'Lajeado do Bugre' },
    { value: 'Lavras do Sul' },
    { value: 'Liberato Salzano' },
    { value: 'Lindolfo Collor' },
    { value: 'Linha Nova' },
    { value: 'Machadinho' },
    { value: 'Maçambará' },
    { value: 'Mampituba' },
    { value: 'Manoel Viana' },
    { value: 'Maquiné' },
    { value: 'Maratá' },
    { value: 'Marau' },
    { value: 'Marcelino Ramos' },
    { value: 'Mariana Pimentel' },
    { value: 'Mariano Moro' },
    { value: 'Marques de Souza' },
    { value: 'Mata' },
    { value: 'Mato Castelhano' },
    { value: 'Mato Leitão' },
    { value: 'Mato Queimado' },
    { value: 'Maximiliano de Almeida' },
    { value: 'Minas do Leão' },
    { value: 'Miraguaí' },
    { value: 'Montauri' },
    { value: 'Monte Alegre dos Campos' },
    { value: 'Monte Belo do Sul' },
    { value: 'Montenegro' },
    { value: 'Mormaço' },
    { value: 'Morrinhos do Sul' },
    { value: 'Morro Redondo' },
    { value: 'Morro Reuter' },
    { value: 'Mostardas' },
    { value: 'Muçum' },
    { value: 'Muitos Capões' },
    { value: 'Muliterno' },
    { value: 'Não-Me-Toque' },
    { value: 'Nicolau Vergueiro' },
    { value: 'Nonoai' },
    { value: 'Nova Alvorada' },
    { value: 'Nova Araçá' },
    { value: 'Nova Bassano' },
    { value: 'Nova Boa Vista' },
    { value: 'Nova Bréscia' },
    { value: 'Nova Candelária' },
    { value: 'Nova Esperança do Sul' },
    { value: 'Nova Hartz' },
    { value: 'Nova Pádua' },
    { value: 'Nova Palma' },
    { value: 'Nova Petrópolis' },
    { value: 'Nova Prata' },
    { value: 'Nova Ramada' },
    { value: 'Nova Roma do Sul' },
    { value: 'Nova Santa Rita' },
    { value: 'Novo Cabrais' },
    { value: 'Novo Hamburgo' },
    { value: 'Novo Machado' },
    { value: 'Novo Tiradentes' },
    { value: 'Novo Xingu' },
    { value: 'Novo Barreiro' },
    { value: 'Osório' },
    { value: 'Paim Filho' },
    { value: 'Palmares do Sul' },
    { value: 'Palmeira das Missões' },
    { value: 'Palmitinho' },
    { value: 'Panambi' },
    { value: 'Pantano Grande' },
    { value: 'Paraí' },
    { value: 'Paraíso do Sul' },
    { value: 'Pareci Novo' },
    { value: 'Parobé' },
    { value: 'Passa Sete' },
    { value: 'Passo do Sobrado' },
    { value: 'Passo Fundo' },
    { value: 'Paulo Bento' },
    { value: 'Paverama' },
    { value: 'Pedras Altas' },
    { value: 'Pedro Osório' },
    { value: 'Pejuçara' },
    { value: 'Pelotas' },
    { value: 'Picada Café' },
    { value: 'Pinhal' },
    { value: 'Pinhal da Serra' },
    { value: 'Pinhal Grande' },
    { value: 'Pinheirinho do Vale' },
    { value: 'Pinheiro Machado' },
    { value: 'Pirapó' },
    { value: 'Piratini' },
    { value: 'Planalto' },
    { value: 'Poço das Antas' },
    { value: 'Pontão' },
    { value: 'Ponte Preta' },
    { value: 'Portão' },
    { value: 'Porto Alegre' },
    { value: 'Porto Lucena' },
    { value: 'Porto Mauá' },
    { value: 'Porto Vera Cruz' },
    { value: 'Porto Xavier' },
    { value: 'Pouso Novo' },
    { value: 'Presidente Lucena' },
    { value: 'Progresso' },
    { value: 'Protásio Alves' },
    { value: 'Putinga' },
    { value: 'Quaraí' },
    { value: 'Quatro Irmãos' },
    { value: 'Quevedos' },
    { value: 'Quinze de Novembro' },
    { value: 'Redentora' },
    { value: 'Relvado' },
    { value: 'Restinga Seca' },
    { value: 'Rio dos Índios' },
    { value: 'Rio Grande' },
    { value: 'Rio Pardo' },
    { value: 'Riozinho' },
    { value: 'Roca Sales' },
    { value: 'Rodeio Bonito' },
    { value: 'Rolador' },
    { value: 'Rolante' },
    { value: 'Ronda Alta' },
    { value: 'Rondinha' },
    { value: 'Roque Gonzales' },
    { value: 'Rosário do Sul' },
    { value: 'Sagrada Família' },
    { value: 'Saldanha Marinho' },
    { value: 'Salto do Jacuí' },
    { value: 'Salvador das Missões' },
    { value: 'Salvador do Sul' },
    { value: 'Sananduva' },
    { value: 'Santa Bárbara do Sul' },
    { value: 'Santa Cecília do Sul' },
    { value: 'Santa Clara do Sul' },
    { value: 'Santa Cruz do Sul' },
    { value: 'Santa Maria' },
    { value: 'Santa Maria do Herval' },
    { value: 'Santa Margarida do Sul' },
    { value: 'Santana da Boa Vista' },
    { value: 'Sant\'Ana do Livramento' },
    { value: 'Santa Rosa' },
    { value: 'Santa Tereza' },
    { value: 'Santa Vitória do Palmar' },
    { value: 'Santiago' },
    { value: 'Santo Ângelo' },
    { value: 'Santo Antônio do Palma' },
    { value: 'Santo Antônio da Patrulha' },
    { value: 'Santo Antônio das Missões' },
    { value: 'Santo Antônio do Planalto' },
    { value: 'Santo Augusto' },
    { value: 'Santo Cristo' },
    { value: 'Santo Expedito do Sul' },
    { value: 'São Borja' },
    { value: 'São Domingos do Sul' },
    { value: 'São Francisco de Assis' },
    { value: 'São Francisco de Paula' },
    { value: 'São Gabriel' },
    { value: 'São Jerônimo' },
    { value: 'São João da Urtiga' },
    { value: 'São João do Polêsine' },
    { value: 'São Jorge' },
    { value: 'São José das Missões' },
    { value: 'São José do Herval' },
    { value: 'São José do Hortêncio' },
    { value: 'São José do Inhacorá' },
    { value: 'São José do Norte' },
    { value: 'São José do Ouro' },
    { value: 'São José do Sul' },
    { value: 'São José dos Ausentes' },
    { value: 'São Leopoldo' },
    { value: 'São Lourenço do Sul' },
    { value: 'São Luiz Gonzaga' },
    { value: 'São Marcos' },
    { value: 'São Martinho' },
    { value: 'São Martinho da Serra' },
    { value: 'São Miguel das Missões' },
    { value: 'São Nicolau' },
    { value: 'São Paulo das Missões' },
    { value: 'São Pedro da Serra' },
    { value: 'São Pedro das Missões' },
    { value: 'São Pedro do Butiá' },
    { value: 'São Pedro do Sul' },
    { value: 'São Sebastião do Caí' },
    { value: 'São Sepé' },
    { value: 'São Valentim' },
    { value: 'São Valentim do Sul' },
    { value: 'São Valério do Sul' },
    { value: 'São Vendelino' },
    { value: 'São Vicente do Sul' },
    { value: 'Sapiranga' },
    { value: 'Sapucaia do Sul' },
    { value: 'Sarandi' },
    { value: 'Seberi' },
    { value: 'Sede Nova' },
    { value: 'Segredo' },
    { value: 'Selbach' },
    { value: 'Senador Salgado Filho' },
    { value: 'Sentinela do Sul' },
    { value: 'Serafina Corrêa' },
    { value: 'Sério' },
    { value: 'Sertão' },
    { value: 'Sertão Santana' },
    { value: 'Sete de Setembro' },
    { value: 'Severiano de Almeida' },
    { value: 'Silveira Martins' },
    { value: 'Sinimbu' },
    { value: 'Sobradinho' },
    { value: 'Soledade' },
    { value: 'Tabaí' },
    { value: 'Tapejara' },
    { value: 'Tapera' },
    { value: 'Tapes' },
    { value: 'Taquara' },
    { value: 'Taquari' },
    { value: 'Taquaruçu do Sul' },
    { value: 'Tavares' },
    { value: 'Tenente Portela' },
    { value: 'Terra de Areia' },
    { value: 'Teutônia' },
    { value: 'Tio Hugo' },
    { value: 'Tiradentes do Sul' },
    { value: 'Toropi' },
    { value: 'Torres' },
    { value: 'Tramandaí' },
    { value: 'Travesseiro' },
    { value: 'Três Arroios' },
    { value: 'Três Cachoeiras' },
    { value: 'Três Coroas' },
    { value: 'Três de Maio' },
    { value: 'Três Forquilhas' },
    { value: 'Três Palmeiras' },
    { value: 'Três Passos' },
    { value: 'Trindade do Sul' },
    { value: 'Triunfo' },
    { value: 'Tucunduva' },
    { value: 'Tunas' },
    { value: 'Tupanci do Sul' },
    { value: 'Tupanciretã' },
    { value: 'Tupandi' },
    { value: 'Tuparendi' },
    { value: 'Turuçu' },
    { value: 'Ubiretama' },
    { value: 'União da Serra' },
    { value: 'Unistalda' },
    { value: 'Uruguaiana' },
    { value: 'Vacaria' },
    { value: 'Vale Verde' },
    { value: 'Vale do Sol' },
    { value: 'Vale Real' },
    { value: 'Vanini' },
    { value: 'Venâncio Aires' },
    { value: 'Vera Cruz' },
    { value: 'Veranópolis' },
    { value: 'Vespasiano Correa' },
    { value: 'Viadutos' },
    { value: 'Viamão' },
    { value: 'Vicente Dutra' },
    { value: 'Victor Graeff' },
    { value: 'Vila Flores' },
    { value: 'Vila Lângaro' },
    { value: 'Vila Maria' },
    { value: 'Vila Nova do Sul' },
    { value: 'Vista Alegre' },
    { value: 'Vista Alegre do Prata' },
    { value: 'Vista Gaúcha' },
    { value: 'Vitória das Missões' },
    { value: 'Westfalia' },
    { value: 'Xangri-lá' },
    { value: 'Água Clara' },
    { value: 'Alcinópolis' },
    { value: 'Amambai' },
    { value: 'Anastácio' },
    { value: 'Anaurilândia' },
    { value: 'Angélica' },
    { value: 'Antônio João' },
    { value: 'Aparecida do Taboado' },
    { value: 'Aquidauana' },
    { value: 'Aral Moreira' },
    { value: 'Bandeirantes' },
    { value: 'Bataguassu' },
    { value: 'Batayporã' },
    { value: 'Bela Vista' },
    { value: 'Bodoquena' },
    { value: 'Bonito' },
    { value: 'Brasilândia' },
    { value: 'Caarapó' },
    { value: 'Camapuã' },
    { value: 'Campo Grande' },
    { value: 'Caracol' },
    { value: 'Cassilândia' },
    { value: 'Chapadão do Sul' },
    { value: 'Corguinho' },
    { value: 'Coronel Sapucaia' },
    { value: 'Corumbá' },
    { value: 'Costa Rica' },
    { value: 'Coxim' },
    { value: 'Deodápolis' },
    { value: 'Dois Irmãos do Buriti' },
    { value: 'Douradina' },
    { value: 'Dourados' },
    { value: 'Eldorado' },
    { value: 'Fátima do Sul' },
    { value: 'Figueirão' },
    { value: 'Glória de Dourados' },
    { value: 'Guia Lopes da Laguna' },
    { value: 'Iguatemi' },
    { value: 'Inocência' },
    { value: 'Itaporã' },
    { value: 'Itaquiraí' },
    { value: 'Ivinhema' },
    { value: 'Japorã' },
    { value: 'Jaraguari' },
    { value: 'Jardim' },
    { value: 'Jateí' },
    { value: 'Juti' },
    { value: 'Ladário' },
    { value: 'Laguna Carapã' },
    { value: 'Maracaju' },
    { value: 'Miranda' },
    { value: 'Mundo Novo' },
    { value: 'Naviraí' },
    { value: 'Nioaque' },
    { value: 'Nova Alvorada do Sul' },
    { value: 'Nova Andradina' },
    { value: 'Novo Horizonte do Sul' },
    { value: 'Paranaíba' },
    { value: 'Paranhos' },
    { value: 'Pedro Gomes' },
    { value: 'Ponta Porã' },
    { value: 'Porto Murtinho' },
    { value: 'Ribas do Rio Pardo' },
    { value: 'Rio Brilhante' },
    { value: 'Rio Negro' },
    { value: 'Rio Verde de Mato Grosso' },
    { value: 'Rochedo' },
    { value: 'Santa Rita do Pardo' },
    { value: 'São Gabriel do Oeste' },
    { value: 'Sete Quedas' },
    { value: 'Selvíria' },
    { value: 'Sidrolândia' },
    { value: 'Sonora' },
    { value: 'Tacuru' },
    { value: 'Taquarussu' },
    { value: 'Terenos' },
    { value: 'Três Lagoas' },
    { value: 'Vicentina' },
    { value: 'Pinto Bandeira' },
];
